// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.BlogModel = (function(_super) {

    __extends(BlogModel, _super);

    function BlogModel() {
      return BlogModel.__super__.constructor.apply(this, arguments);
    }

    BlogModel.configure("BlogModel", "title", "content", "date", "likes");

    BlogModel.extend(Spine.Model.Ajax);

    return BlogModel;

  })(Spine.Model);

}).call(this);
