// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.BlogView = (function(_super) {
    var TPL;

    __extends(BlogView, _super);

    TPL = Handlebars.compile($('#blogContent-template').html());

    function BlogView() {
      this.render = __bind(this.render, this);
      BlogView.__super__.constructor.apply(this, arguments);
    }

    BlogView.prototype.render = function() {
      this.replace(TPL(this.blogModel));
      return this;
    };

    return BlogView;

  })(Spine.Controller);

}).call(this);
