// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.DocModel = (function(_super) {

    __extends(DocModel, _super);

    function DocModel() {
      return DocModel.__super__.constructor.apply(this, arguments);
    }

    DocModel.configure("DocModel", "text", "date", "filepath");

    DocModel.extend(Spine.Model.Ajax);

    return DocModel;

  })(Spine.Model);

}).call(this);
