// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.DocView = (function(_super) {
    var TPL;

    __extends(DocView, _super);

    TPL = Handlebars.compile($('#doc-template').html());

    function DocView() {
      this.render = __bind(this.render, this);
      DocView.__super__.constructor.apply(this, arguments);
    }

    DocView.prototype.render = function() {
      this.replace(TPL(this.docModel));
      return this;
    };

    return DocView;

  })(Spine.Controller);

}).call(this);
